spring:
  datasource:
    password: ${DATA_PASSWORD}
    url: jdbc:mysql://localhost:3306/plant_me?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DATA_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: TRUE
        show_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never
logging:
  level:
    org: warn
    blog: warn
    hibernate:
      SQL: debug
      type:
        descriptor: trace

weather:
  api:
    url: "https://api.open-meteo.com/v1/forecast?latitude=42.15&longitude=24.75&current=temperature_2m,is_day,rain,cloud_cover,wind_speed_10m"

attempts:
  api:
    baseUrl: "http://localhost:8081/attempts"
